version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Settings__ActivityClient__Token=${ACTIVITY_CLIENT_TOKEN}
      - Settings__Bot__ApiToken=${TEST_BOT_TOKEN}
      - Settings__Bot__ChannelId=${TEST_BOT_CHANNEL_ID}
      - Settings__Bot__Admins=${ADMINS}
    volumes:
      - ./booking-config.json:./booking-config.json:rw
    ports:
      - 5000:5000